2024-04-28 00:11:48,834 [MainThread  ] [INFO ]  logging in using static token
2024-04-28 00:11:49,715 [MainThread  ] [INFO ]  Shard ID None has connected to Gateway (Session ID: cffb68a1c21ab652bb04e6325ddfa909).
2024-04-28 00:11:54,594 [MainThread  ] [INFO ]  Connecting to voice...
2024-04-28 00:11:54,595 [MainThread  ] [INFO ]  Starting voice handshake... (connection attempt 1)
2024-04-28 00:11:54,904 [MainThread  ] [INFO ]  Voice handshake complete. Endpoint found buenos-aires9019.discord.media
2024-04-28 00:11:57,443 [MainThread  ] [ERROR]  Ignoring exception in command queue
Traceback (most recent call last):
  File "/home/santi/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/CarpBot/musiccommands.py", line 216, in queue
    embed = b.print_queue(playlist, arg, looping, ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/CarpBot/music.py", line 142, in print_queue
    time_left = self.calculate_queue_time(start_time, playlist, cplaying, vc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/CarpBot/music.py", line 273, in calculate_queue_time
    x = time.strptime(start_time.split(',')[0], '%H:%M:%S')
                      ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/santi/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/santi/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'split'
2024-04-28 00:12:07,001 [Thread-3    ] [INFO ]  ffmpeg process 55106 has not terminated. Waiting to terminate...
2024-04-28 00:12:07,006 [Thread-3    ] [INFO ]  ffmpeg process 55106 should have terminated with a return code of -9.
2024-04-28 00:12:15,130 [Thread-4    ] [INFO ]  ffmpeg process 55127 has not terminated. Waiting to terminate...
2024-04-28 00:12:15,136 [Thread-4    ] [INFO ]  ffmpeg process 55127 should have terminated with a return code of -9.
2024-04-28 00:12:29,906 [Thread-5    ] [INFO ]  ffmpeg process 55152 has not terminated. Waiting to terminate...
2024-04-28 00:12:29,912 [Thread-5    ] [INFO ]  ffmpeg process 55152 should have terminated with a return code of -9.
2024-04-28 00:15:09,708 [MainThread  ] [INFO ]  The voice handshake is being terminated for Channel ID 1062966247752474658 (Guild ID 1062966247752474654)
2024-04-28 00:15:09,708 [MainThread  ] [INFO ]  Disconnecting from voice normally, close code 1000.
2024-04-28 00:15:09,712 [Thread-6    ] [INFO ]  ffmpeg process 55172 has not terminated. Waiting to terminate...
2024-04-28 00:15:09,716 [Thread-6    ] [INFO ]  ffmpeg process 55172 should have terminated with a return code of -9.
